services:
  app:
    build:
      context: .
      target: dev
    platform: linux/arm64
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./data:/app/data
      - ./tessdata:/tessdata
    env_file: .env.local
    restart: unless-stopped
